services:
  money_report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/vendor
      - /app/node_modules
    ports:
      - "8000:8000"
    command: >
      sh -c "
      php artisan serve --host=0.0.0.0 --port=8000
      "
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge